name: KarIntensify
main: vip.mcsj.www.main.KarIntensify
version: 1.4.2
api-version: 1.13
author: Karounac58
depend:
  - NBTAPI
commands:
  karintensify:
    usage: "/karintenfisy <player-name> <number>"
    description: ""
    permission: "karintensify.use"
    permission-message: "You don't have the permission to do that"